const leaveRequests = [
  {
    id: 1,
    employeeName: 'Anita Sharma',
    employeeId: 'EMP101',
    leaveType: 'Sick Leave',
    startDate: '2025-04-25',
    endDate: '2025-04-27',
    reason: 'Fever and weakness',
    status: 'Pending',
  },
  {
    id: 2,
    employeeName: 'Rahul Kumar',
    employeeId: 'EMP102',
    leaveType: 'Casual Leave',
    startDate: '2025-04-28',
    endDate: '2025-04-29',
    reason: 'Family function',
    status: 'Approved',
  },
  {
    id: 3,
    employeeName: 'Nehanth varma',
    employeeId: 'EMP103',
    leaveType: 'Maternity Leave',
    startDate: '2025-05-01',
    endDate: '2025-08-01',
    reason: 'Childbirth',
    status: 'Approved',
  },
  {
    id: 4,
    employeeName: 'Karani',
    employeeId: 'EMP104',
    leaveType: 'Sick Leave',
    startDate: '2025-04-22',
    endDate: '2025-04-23',
    reason: 'Flu symptoms',
    status: 'Rejected',
  },
  {
    id: 5,
    employeeName: 'Priyanka',
    employeeId: 'EMP105',
    leaveType: 'Casual Leave',
    startDate: '2025-05-10',
    endDate: '2025-05-11',
    reason: 'Personal work',
    status: 'Pending',
  },
  {
    id: 6,
    employeeName: 'Amit Patel',
    employeeId: 'EMP106',
    leaveType: 'Earned Leave',
    startDate: '2025-05-15',
    endDate: '2025-05-20',
    reason: 'Vacation',
    status: 'Pending',
  },
  {
    id: 7,
    employeeName: 'Sunita',
    employeeId: 'EMP107',
    leaveType: 'Casual Leave',
    startDate: '2025-04-30',
    endDate: '2025-05-01',
    reason: 'Travel',
    status: 'Approved',
  },
  {
    id: 8,
    employeeName: 'Manoj Kumar',
    employeeId: 'EMP108',
    leaveType: 'Sick Leave',
    startDate: '2025-04-21',
    endDate: '2025-04-24',
    reason: 'Migraine',
    status: 'Rejected',
  },
  {
    id: 9,
    employeeName: 'Rishitha',
    employeeId: 'EMP109',
    leaveType: 'Casual Leave',
    startDate: '2025-05-05',
    endDate: '2025-05-06',
    reason: 'Family trip',
    status: 'Pending',
  },
  {
    id: 10,
    employeeName: 'Kiran',
    employeeId: 'EMP110',
    leaveType: 'Earned Leave',
    startDate: '2025-06-01',
    endDate: '2025-06-10',
    reason: 'Long vacation',
    status: 'Pending',
  },
];

export default leaveRequests;
