# Generated by Django 5.2.1 on 2025-05-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0003_holiday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
