# Generated by Django 5.2.1 on 2025-05-27 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0003_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profiles',
        ),
    ]
