# Generated by Django 5.2.1 on 2025-05-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0004_delete_announcement_delete_holiday'),
        ('corevolthrm', '0006_employee'),
    ]

    operations = [
    ]
