# Generated by Django 5.2.1 on 2025-05-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0009_leaveapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
