# Generated by Django 5.2.1 on 2025-05-29 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0010_delete_announcement_employee_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(1990, 1, 1), null=True),
        ),
    ]
