# Generated by Django 5.2.1 on 2025-05-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0004_rename_profile_profiles'),
        ('corevolthrm', '0011_alter_employee_birthday'),
    ]

    operations = [
    ]
