# Generated by Django 5.2.1 on 2025-05-30 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0010_worksession_break'),
        ('corevolthrm', '0012_merge_20250529_1719'),
    ]

    operations = [
    ]
