# Generated by Django 5.2.1 on 2025-06-04 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0015_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamname',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Employee who manages this team', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_teams', to='corevolthrm.employee'),
        ),
        migrations.AddField(
            model_name='teamname',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Team members', related_name='teams', to='corevolthrm.employee'),
        ),
    ]
