# Generated by Django 5.2.1 on 2025-06-04 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0016_teamname_manager_teamname_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('Aadhar Card', 'Aadhar Card'), ('Driving Licence', 'Driving Licence'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Education', 'Education'), ('Experience', 'Experience')], max_length=20)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('institute', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='upload-documents/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='corevolthrm.profiles')),
            ],
        ),
    ]
