# Generated by Django 5.2.1 on 2025-06-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corevolthrm", "0016_teamname_manager_teamname_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="reports_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to="corevolthrm.employee",
            ),
        ),
    ]
