# Generated by Django 5.2.1 on 2025-06-02 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0016_teamname_manager_teamname_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in_hours', models.IntegerField()),
                ('description', models.CharField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corevolthrm.worksession')),
            ],
        ),
    ]
