# Generated by Django 5.2.1 on 2025-06-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0018_worksession_approval_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheetdetails',
            old_name='time_in_hours',
            new_name='hourSpent',
        ),
    ]
