# Generated by Django 5.2.1 on 2025-06-03 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0019_rename_time_in_hours_timesheetdetails_hourspent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetdetails',
            name='session_id',
        ),
        migrations.AddField(
            model_name='timesheetdetails',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_details', to='corevolthrm.worksession'),
        ),
    ]
