# Generated by Django 5.2.1 on 2025-06-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0020_remove_timesheetdetails_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='next_clock_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
