# Generated by Django 5.2.1 on 2025-06-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0017_employee_reports_to'),
        ('corevolthrm', '0021_worksession_next_clock_in'),
    ]

    operations = [
    ]
