# Generated by Django 5.2.1 on 2025-06-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0022_merge_20250606_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Submitted', 'Submitted')], default='Pending', max_length=20),
        ),
    ]
