# Generated by Django 5.2.1 on 2025-06-09 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0017_uploaddocument'),
        ('corevolthrm', '0022_merge_20250606_1727'),
    ]

    operations = [
    ]
