# Generated by Django 5.2.1 on 2025-06-09 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0023_merge_0017_uploaddocument_0022_merge_20250606_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='reports_to',
        ),
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='corevolthrm.profiles'),
        ),
    ]
