# Generated by Django 5.2.1 on 2025-06-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0023_alter_worksession_approval_status'),
        ('corevolthrm', '0024_remove_employee_reports_to_employee_profile'),
    ]

    operations = [
    ]
