# Generated by Django 5.2.1 on 2025-06-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0025_merge_20250620_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamname',
            name='total_members',
        ),
    ]
